/**
 * backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PriorityLevelDto } from './priorityLevelDto';
import { TodoListDto } from './todoListDto';

export interface TodosVm { 
    priorityLevels?: Array<PriorityLevelDto>;
    lists?: Array<TodoListDto>;
}